package pagesOfYasasiiWeb;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import com.baseYasasiiWeb.PageFactoryInitYasasiiWeb;

public class bedCreation extends PageFactoryInitYasasiiWeb{

	private static final char B = 0;


	public bedCreation(WebDriver driver) {
		super(driver);

	}

	@FindBy(xpath = "//a[@class='nav-link navbar-brand menu']//div[@class='menu-toggle']")
	public WebElement Menutoggle;

	@FindBy(xpath = "//i[@class='ki ki-cog']")
	public WebElement mastericon;

	@FindBy(xpath = "//div[@class='link-value'][normalize-space()='Resource']")
	public WebElement resource; 

	@FindBy(xpath = "//div[normalize-space()='Resource Master']")
	public WebElement resourceMaster; 

	@FindBy(xpath = "//input[@id='resourcecategory']")
	public WebElement category; 

	@FindBy(xpath = "//input[@id='roomid']")
	public WebElement ROOMcategory;

	@FindBy(xpath = "//div[@title='A1 Block-Ground floor-Deluxe-Deluxe Room']")
	public WebElement  deluxRoom;
	
	@FindBy(xpath = "//div[@title='A1 Block-Ground floor-Ultra-Deluxe-Ultra-Deluxe Room']")
	public WebElement  ultradeluxRoom;

	@FindBy(xpath = "//div[@title='A1 Block-Ground floor-ER_Exclusive-Emergency care']")
	public WebElement  emrgncyRoom;

	@FindBy(xpath = "//i[@class='ki ki-pencil']")
	public WebElement Edit;

	@FindBy(xpath = "//input[@id='bedtype']")
	public WebElement BedType;

	@FindBy(xpath = "//input[@id='nursingstation']")
	public WebElement nurestation;

	@FindBy(xpath = "//input[@id='bedname']")
	public WebElement bedname;

	@FindBy(xpath = "//span[@class='icon-btn btn-dark-green inline']")
	public WebElement bedAdd;

	@FindBy(xpath = "//button[@id='resourcemasterupdate']")
	public WebElement update;

	@FindBy(xpath = "//div[@class='form-group zero-bottom ki-dropdown']//input[@id='floorid']")
	public WebElement floor;


	@FindBy(xpath = "//div[@class='form-group zero-bottom ki-dropdown']//input[@id='roomid']")
	public WebElement RoomWard;





	public void ultradeluxe() throws InterruptedException {

		Thread.sleep(2000);
		Menutoggle.click();
		Thread.sleep(600);
		mastericon.click();
		Thread.sleep(600);
		JavascriptExecutor js= (JavascriptExecutor) driver;
		js.executeScript("arguments[0].scrollIntoView();", resource );
		Thread.sleep(600);
		resource.click();
		Thread.sleep(600);
		resourceMaster.click();
		Thread.sleep(2000);
		category.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Bed']")).click();                                  
		Thread.sleep(600);
		driver.findElement(By.xpath("/html[1]/body[1]/app-root[1]/app-layout[1]/main[1]/app-resourcemaster[1]/div[1]/lib-searchbarlist[1]/div[1]/div[2]/form[1]/div[3]/div[1]/ki-select-control[1]/div[1]/input[1]")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='A1 Block']")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//div[@class='form-group zero-bottom ki-dropdown']//input[@id='floorid']")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Ground floor']")).click();

		ROOMcategory.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Deluxe Room']")).click();
//		
//		Thread.sleep(600);
//		driver.findElement(By.xpath("//li[normalize-space()='Ultra-Deluxe Room']")).click();
		Thread.sleep(600);
		deluxRoom.click();
		Thread.sleep(600);
//		
//		ultradeluxRoom.click();
//		Thread.sleep(600);
		Edit.click();
		Thread.sleep(600);
		BedType.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Normal']")).click();
		Thread.sleep(600);
		nurestation.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Emergency NS']")).click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-700");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-701");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-702");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-703");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-704");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-705");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-706");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-707");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-708");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-709");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-710");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-711");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-712");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-713");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-714");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-715");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-716");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-717");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-718");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-719");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-720");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-721");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-722");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-723");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-724");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-725");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-726");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-727");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-728");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-729");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-730");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-731");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-732");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-733");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-734");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-735");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-736");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-737");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-738");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-739");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-740");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-741");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-742");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-743");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-744");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-745");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-746");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-747");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-748");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-749");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-750");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-751");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-752");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-753");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-754");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-755");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-756");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-757");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-758");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-759");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-760");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-761");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-762");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-763");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-764");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-765");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-766");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-767");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-768");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-769");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);

		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-770");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-771");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-772");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-773");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-774");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-775");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-776");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-777");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-778");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-779");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-780");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-781");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-782");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-783");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-784");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-785");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-786");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-787");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-788");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-789");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-790");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-791");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-792");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-793");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-794");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-795");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-796");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-797");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-798");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-799");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		update.click();
		Thread.sleep(2000);
		
		
		
		
	}

	public void bed() throws InterruptedException {

		int  a=06;
		char b=71;


		Thread.sleep(2000);
		Menutoggle.click();
		Thread.sleep(600);
		mastericon.click();
		Thread.sleep(600);
		JavascriptExecutor js= (JavascriptExecutor) driver;
		js.executeScript("arguments[0].scrollIntoView();", resource );
		Thread.sleep(600);
		resource.click();
		Thread.sleep(600);
		resourceMaster.click();
		Thread.sleep(2000);
		category.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Bed']")).click();                                  
		Thread.sleep(600);
		driver.findElement(By.xpath("/html[1]/body[1]/app-root[1]/app-layout[1]/main[1]/app-resourcemaster[1]/div[1]/lib-searchbarlist[1]/div[1]/div[2]/form[1]/div[3]/div[1]/ki-select-control[1]/div[1]/input[1]")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='A1 Block']")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//div[@class='form-group zero-bottom ki-dropdown']//input[@id='floorid']")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Ground floor']")).click();

		ROOMcategory.click();
		Thread.sleep(600);
//		driver.findElement(By.xpath("//li[normalize-space()='Ultra-Deluxe Room']")).click();
//		Thread.sleep(600);
//		ultradeluxRoom.click();
//		Thread.sleep(600);
		
		driver.findElement(By.xpath("//li[normalize-space()='Deluxe Room']")).click();
		Thread.sleep(600);
		deluxRoom.click();
		Thread.sleep(600);
	
		Edit.click();
		Thread.sleep(600);
		BedType.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Normal']")).click();
		Thread.sleep(600);
		nurestation.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Emergency NS']")).click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"0");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"1");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"2");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"3");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"4");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"5");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"6");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		//nurestation.click();
		Thread.sleep(600);
		//driver.findElement(By.xpath("//li[normalize-space()='Ward Nure_Nursing station']")).click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"7");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"8");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"9");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		//	bedname.sendKeys("ANS-740");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);  
		nurestation.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Transfer nursing station']")).click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-1"+b+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-2"+b+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-3"+b+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-4"+b+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		nurestation.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Emergency NS']")).click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-5"+b+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-6"+b+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-7"+b+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-8"+b+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-9"+b+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-10"+b+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		update.click();
		Thread.sleep(2000);






		////////////////////Emergency beds


		category.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Bed']")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("/html[1]/body[1]/app-root[1]/app-layout[1]/main[1]/app-resourcemaster[1]/div[1]/lib-searchbarlist[1]/div[1]/div[2]/form[1]/div[3]/div[1]/ki-select-control[1]/div[1]/input[1]")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='A1 Block']")).click();
		Thread.sleep(600);
		floor.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Ground floor']")).click();
		Thread.sleep(600);
		RoomWard.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Emergency care']")).click();
		Thread.sleep(600);
		emrgncyRoom.click();
		Thread.sleep(600);
		Edit.click();
		Thread.sleep(600);
		BedType.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Normal']")).click();
		Thread.sleep(600);
		nurestation.click();	
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Emergency NS']")).click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"0");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"1");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"2");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"3");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"4");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"5");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"6");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		//nurestation.click();
		Thread.sleep(600);
		//driver.findElement(By.xpath("//li[normalize-space()='Ward Nure_Nursing station']")).click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"7");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"8");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"9");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		//	bedname.sendKeys("ANS-740");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		update.click();
		Thread.sleep(2000);








	}


}
